### ISSUE TITLE
Bug identified when unitID>9

### ISSUE THREAD

**Issue by scastoldiprivate** [Sennevds/RFXcomIdGenerator#7]
For example, the following command :
python generateId.py -t Lighting1 -s ARC -p C,11
gives 07100100430110000, which is invalid in Home Assistant.
Problem appears when unitID is >9
UnitID should be one hex digit in the result
Correct result is : 07100100430B0000

Same for command :
python generateId.py -t Lighting1 -s ARC -p D,12
gives : 07100100440120000 (invalid)
should give 07100100440C0000 

Both of these examples were verified and working with Home Assistant v2023.7.3 with a RFXCOM RFX433XL and 2 working remote plug switches.

**Comment by zombiefredrik** [comment]
@scastoldiprivate fixed in pull request - don't know if this project is alive, but I just needed it for some old waveman stuff, and since I was in the code ...

**Comment by Sennevds** [comment]
I'm not updating the project myself because I don't need it anymore but if there are PR's I will gladly approve them
